/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedComposeRouteImport } from './routes/_authenticated/compose'
import { Route as AuthenticatedCreateGroupRouteImport } from './routes/_authenticated/create-group'
import { Route as AuthenticatedDonateRouteImport } from './routes/_authenticated/donate'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedLoveRouteImport } from './routes/_authenticated/love'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStoryRouteImport } from './routes/_authenticated/story'
import { Route as AuthenticatedButtonPagePageIdRouteImport } from './routes/_authenticated/button-page.$pageId'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedMessagesUserIdRouteImport } from './routes/_authenticated/messages.$userId'
import { Route as AuthenticatedPostPostIdRouteImport } from './routes/_authenticated/post.$postId'
import { Route as AuthenticatedViewButtonPagePageIdRouteImport } from './routes/_authenticated/view-button-page.$pageId'
import { Route as AuthenticatedMessagesGroupGroupIdRouteImport } from './routes/_authenticated/messages.group.$groupId'
import { Route as AuthenticatedStoryViewStoryIdRouteImport } from './routes/_authenticated/story.view.$storyId'
import { Route as AuthenticatedUUsernameIndexRouteImport } from './routes/_authenticated/u.$username/index'
import { Route as AuthenticatedUUsernameFollowersRouteImport } from './routes/_authenticated/u.$username/followers'
import { Route as AuthenticatedUUsernameFollowingRouteImport } from './routes/_authenticated/u.$username/following'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedComposeRoute = AuthenticatedComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateGroupRoute =
  AuthenticatedCreateGroupRouteImport.update({
    id: '/create-group',
    path: '/create-group',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDonateRoute = AuthenticatedDonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLoveRoute = AuthenticatedLoveRouteImport.update({
  id: '/love',
  path: '/love',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoryRoute = AuthenticatedStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedButtonPagePageIdRoute =
  AuthenticatedButtonPagePageIdRouteImport.update({
    id: '/button-page/$pageId',
    path: '/button-page/$pageId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesUserIdRoute =
  AuthenticatedMessagesUserIdRouteImport.update({
    id: '/messages/$userId',
    path: '/messages/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPostPostIdRoute = AuthenticatedPostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedViewButtonPagePageIdRoute =
  AuthenticatedViewButtonPagePageIdRouteImport.update({
    id: '/view-button-page/$pageId',
    path: '/view-button-page/$pageId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesGroupGroupIdRoute =
  AuthenticatedMessagesGroupGroupIdRouteImport.update({
    id: '/messages/group/$groupId',
    path: '/messages/group/$groupId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoryViewStoryIdRoute =
  AuthenticatedStoryViewStoryIdRouteImport.update({
    id: '/view/$storyId',
    path: '/view/$storyId',
    getParentRoute: () => AuthenticatedStoryRoute,
  } as any)
const AuthenticatedUUsernameIndexRoute =
  AuthenticatedUUsernameIndexRouteImport.update({
    id: '/u/$username/',
    path: '/u/$username/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUUsernameFollowersRoute =
  AuthenticatedUUsernameFollowersRouteImport.update({
    id: '/u/$username/followers',
    path: '/u/$username/followers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUUsernameFollowingRoute =
  AuthenticatedUUsernameFollowingRouteImport.update({
    id: '/u/$username/following',
    path: '/u/$username/following',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compose': typeof AuthenticatedComposeRoute
  '/create-group': typeof AuthenticatedCreateGroupRoute
  '/donate': typeof AuthenticatedDonateRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/love': typeof AuthenticatedLoveRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/story': typeof AuthenticatedStoryRouteWithChildren
  '/button-page/$pageId': typeof AuthenticatedButtonPagePageIdRoute
  '/messages/$userId': typeof AuthenticatedMessagesUserIdRoute
  '/post/$postId': typeof AuthenticatedPostPostIdRoute
  '/view-button-page/$pageId': typeof AuthenticatedViewButtonPagePageIdRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/messages/group/$groupId': typeof AuthenticatedMessagesGroupGroupIdRoute
  '/story/view/$storyId': typeof AuthenticatedStoryViewStoryIdRoute
  '/u/$username/followers': typeof AuthenticatedUUsernameFollowersRoute
  '/u/$username/following': typeof AuthenticatedUUsernameFollowingRoute
  '/u/$username/': typeof AuthenticatedUUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compose': typeof AuthenticatedComposeRoute
  '/create-group': typeof AuthenticatedCreateGroupRoute
  '/donate': typeof AuthenticatedDonateRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/love': typeof AuthenticatedLoveRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/story': typeof AuthenticatedStoryRouteWithChildren
  '/button-page/$pageId': typeof AuthenticatedButtonPagePageIdRoute
  '/messages/$userId': typeof AuthenticatedMessagesUserIdRoute
  '/post/$postId': typeof AuthenticatedPostPostIdRoute
  '/view-button-page/$pageId': typeof AuthenticatedViewButtonPagePageIdRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/messages/group/$groupId': typeof AuthenticatedMessagesGroupGroupIdRoute
  '/story/view/$storyId': typeof AuthenticatedStoryViewStoryIdRoute
  '/u/$username/followers': typeof AuthenticatedUUsernameFollowersRoute
  '/u/$username/following': typeof AuthenticatedUUsernameFollowingRoute
  '/u/$username': typeof AuthenticatedUUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/compose': typeof AuthenticatedComposeRoute
  '/_authenticated/create-group': typeof AuthenticatedCreateGroupRoute
  '/_authenticated/donate': typeof AuthenticatedDonateRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/love': typeof AuthenticatedLoveRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/story': typeof AuthenticatedStoryRouteWithChildren
  '/_authenticated/button-page/$pageId': typeof AuthenticatedButtonPagePageIdRoute
  '/_authenticated/messages/$userId': typeof AuthenticatedMessagesUserIdRoute
  '/_authenticated/post/$postId': typeof AuthenticatedPostPostIdRoute
  '/_authenticated/view-button-page/$pageId': typeof AuthenticatedViewButtonPagePageIdRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/messages/group/$groupId': typeof AuthenticatedMessagesGroupGroupIdRoute
  '/_authenticated/story/view/$storyId': typeof AuthenticatedStoryViewStoryIdRoute
  '/_authenticated/u/$username/followers': typeof AuthenticatedUUsernameFollowersRoute
  '/_authenticated/u/$username/following': typeof AuthenticatedUUsernameFollowingRoute
  '/_authenticated/u/$username/': typeof AuthenticatedUUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/compose'
    | '/create-group'
    | '/donate'
    | '/feed'
    | '/love'
    | '/search'
    | '/settings'
    | '/story'
    | '/button-page/$pageId'
    | '/messages/$userId'
    | '/post/$postId'
    | '/view-button-page/$pageId'
    | '/messages/'
    | '/messages/group/$groupId'
    | '/story/view/$storyId'
    | '/u/$username/followers'
    | '/u/$username/following'
    | '/u/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/compose'
    | '/create-group'
    | '/donate'
    | '/feed'
    | '/love'
    | '/search'
    | '/settings'
    | '/story'
    | '/button-page/$pageId'
    | '/messages/$userId'
    | '/post/$postId'
    | '/view-button-page/$pageId'
    | '/messages'
    | '/messages/group/$groupId'
    | '/story/view/$storyId'
    | '/u/$username/followers'
    | '/u/$username/following'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/compose'
    | '/_authenticated/create-group'
    | '/_authenticated/donate'
    | '/_authenticated/feed'
    | '/_authenticated/love'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/story'
    | '/_authenticated/button-page/$pageId'
    | '/_authenticated/messages/$userId'
    | '/_authenticated/post/$postId'
    | '/_authenticated/view-button-page/$pageId'
    | '/_authenticated/messages/'
    | '/_authenticated/messages/group/$groupId'
    | '/_authenticated/story/view/$storyId'
    | '/_authenticated/u/$username/followers'
    | '/_authenticated/u/$username/following'
    | '/_authenticated/u/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/compose': {
      id: '/_authenticated/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof AuthenticatedComposeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create-group': {
      id: '/_authenticated/create-group'
      path: '/create-group'
      fullPath: '/create-group'
      preLoaderRoute: typeof AuthenticatedCreateGroupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/donate': {
      id: '/_authenticated/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof AuthenticatedDonateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/love': {
      id: '/_authenticated/love'
      path: '/love'
      fullPath: '/love'
      preLoaderRoute: typeof AuthenticatedLoveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/story': {
      id: '/_authenticated/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof AuthenticatedStoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/button-page/$pageId': {
      id: '/_authenticated/button-page/$pageId'
      path: '/button-page/$pageId'
      fullPath: '/button-page/$pageId'
      preLoaderRoute: typeof AuthenticatedButtonPagePageIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/$userId': {
      id: '/_authenticated/messages/$userId'
      path: '/messages/$userId'
      fullPath: '/messages/$userId'
      preLoaderRoute: typeof AuthenticatedMessagesUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post/$postId': {
      id: '/_authenticated/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof AuthenticatedPostPostIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/view-button-page/$pageId': {
      id: '/_authenticated/view-button-page/$pageId'
      path: '/view-button-page/$pageId'
      fullPath: '/view-button-page/$pageId'
      preLoaderRoute: typeof AuthenticatedViewButtonPagePageIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/group/$groupId': {
      id: '/_authenticated/messages/group/$groupId'
      path: '/messages/group/$groupId'
      fullPath: '/messages/group/$groupId'
      preLoaderRoute: typeof AuthenticatedMessagesGroupGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/story/view/$storyId': {
      id: '/_authenticated/story/view/$storyId'
      path: '/view/$storyId'
      fullPath: '/story/view/$storyId'
      preLoaderRoute: typeof AuthenticatedStoryViewStoryIdRouteImport
      parentRoute: typeof AuthenticatedStoryRoute
    }
    '/_authenticated/u/$username/': {
      id: '/_authenticated/u/$username/'
      path: '/u/$username'
      fullPath: '/u/$username/'
      preLoaderRoute: typeof AuthenticatedUUsernameIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/u/$username/followers': {
      id: '/_authenticated/u/$username/followers'
      path: '/u/$username/followers'
      fullPath: '/u/$username/followers'
      preLoaderRoute: typeof AuthenticatedUUsernameFollowersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/u/$username/following': {
      id: '/_authenticated/u/$username/following'
      path: '/u/$username/following'
      fullPath: '/u/$username/following'
      preLoaderRoute: typeof AuthenticatedUUsernameFollowingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedStoryRouteChildren {
  AuthenticatedStoryViewStoryIdRoute: typeof AuthenticatedStoryViewStoryIdRoute
}

const AuthenticatedStoryRouteChildren: AuthenticatedStoryRouteChildren = {
  AuthenticatedStoryViewStoryIdRoute: AuthenticatedStoryViewStoryIdRoute,
}

const AuthenticatedStoryRouteWithChildren =
  AuthenticatedStoryRoute._addFileChildren(AuthenticatedStoryRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedComposeRoute: typeof AuthenticatedComposeRoute
  AuthenticatedCreateGroupRoute: typeof AuthenticatedCreateGroupRoute
  AuthenticatedDonateRoute: typeof AuthenticatedDonateRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedLoveRoute: typeof AuthenticatedLoveRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStoryRoute: typeof AuthenticatedStoryRouteWithChildren
  AuthenticatedButtonPagePageIdRoute: typeof AuthenticatedButtonPagePageIdRoute
  AuthenticatedMessagesUserIdRoute: typeof AuthenticatedMessagesUserIdRoute
  AuthenticatedPostPostIdRoute: typeof AuthenticatedPostPostIdRoute
  AuthenticatedViewButtonPagePageIdRoute: typeof AuthenticatedViewButtonPagePageIdRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
  AuthenticatedMessagesGroupGroupIdRoute: typeof AuthenticatedMessagesGroupGroupIdRoute
  AuthenticatedUUsernameFollowersRoute: typeof AuthenticatedUUsernameFollowersRoute
  AuthenticatedUUsernameFollowingRoute: typeof AuthenticatedUUsernameFollowingRoute
  AuthenticatedUUsernameIndexRoute: typeof AuthenticatedUUsernameIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedComposeRoute: AuthenticatedComposeRoute,
  AuthenticatedCreateGroupRoute: AuthenticatedCreateGroupRoute,
  AuthenticatedDonateRoute: AuthenticatedDonateRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedLoveRoute: AuthenticatedLoveRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStoryRoute: AuthenticatedStoryRouteWithChildren,
  AuthenticatedButtonPagePageIdRoute: AuthenticatedButtonPagePageIdRoute,
  AuthenticatedMessagesUserIdRoute: AuthenticatedMessagesUserIdRoute,
  AuthenticatedPostPostIdRoute: AuthenticatedPostPostIdRoute,
  AuthenticatedViewButtonPagePageIdRoute:
    AuthenticatedViewButtonPagePageIdRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
  AuthenticatedMessagesGroupGroupIdRoute:
    AuthenticatedMessagesGroupGroupIdRoute,
  AuthenticatedUUsernameFollowersRoute: AuthenticatedUUsernameFollowersRoute,
  AuthenticatedUUsernameFollowingRoute: AuthenticatedUUsernameFollowingRoute,
  AuthenticatedUUsernameIndexRoute: AuthenticatedUUsernameIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
